character count plugin
wepublish/dreifuss-wysiwyg-editor pull request #11
Opened 2021-07-14 10:23 UTC by bishoymelek

2021-07-27 11:08 UTC, roosnic1 requested changes
Looks very good just some minor changes

2021-07-27 11:08 UTC, roosnic1 commented on packages/core/src/DreifussWysiwygEditor.tsx
> +          {'Characters count:'} <CharCountToolbar />
can you replace the text with an icon? Trying to avoid text because of translations.

2021-07-27 11:08 UTC, roosnic1 commented on packages/core/src/DreifussWysiwygEditor.tsx
> +  const charCount = useCharacterCount()
if you call it `useCharacterCount()` it sounds like a React hook. But as far as i can tell it's not. Either rename it or make it a proper React hook.

2021-07-27 11:08 UTC, roosnic1 commented on packages/core/src/DreifussWysiwygEditorDemo.tsx
> +      showCharCount
Rename this to `showCharactersCount` and set it to `true`. Always work with values.

2021-07-27 11:26 UTC, bishoymelek commented on packages/character-count-ui/package.json
> +  "version": "1.0.2-alpha.1",
@roosnic1 why don't we have the same version at the moment for all as we are just starting with the first working version?

2021-07-27 12:38 UTC, roosnic1 commented on packages/character-count-ui/package.json
> +  "version": "1.0.2-alpha.1",
Lerna is handling this.

2021-07-30 10:06 UTC, HanaAyman approved these changes

2021-08-02 15:02 UTC, merged