f/WPC-467-hotkeys-working
wepublish/dreifuss-wysiwyg-editor pull request #23
Opened 2021-09-16 01:59 UTC by bishoymelek

Now hot keys are working properly again. It was mainly because React can't really handle async/await in events. so I changed the way we are having a promise.

2021-09-21 07:34 UTC, camilleory approved these changes

2021-09-23 22:28 UTC, penk85 approved these changes

2021-09-27 07:44 UTC, roosnic1 requested changes
In Firefox v92 i get the following error 
![image](https://user-images.githubusercontent.com/2340416/134865575-d0868bf4-351f-4513-b3ae-91bc3abfd326.png)

2021-09-27 11:57 UTC, camilleory approved these changes

2021-09-27 13:33 UTC, lakeside763 approved these changes
the editor works fine

2021-09-30 09:05 UTC, roosnic1 approved these changes
awesome 🎉

2021-09-30 09:08 UTC, merged